lstm:
  _target_: src.rul_models.blocks.LSTMBlock
  _args_:
    - _target_: torch.nn.LSTM
      input_size: 17
      num_layers: 2
      dropout: 0.1
      hidden_size: 50
      batch_first: true
      bidirectional: false

    - _target_: torch.nn.Tanh

    - _target_: torch.nn.Dropout
      p: 0.25
  output_size: 34
