regressor:
  _target_: src.rul_models.blocks.Regressor
  _args_:
    - target_: torch.nn.Linear
      in_features: 34
      out_features: 17

    - target_: torch.nn.Sigmoid
    - target_: torch.nn.Dropout
      p: 0.25

    - target_: torch.nn.Linear
      in_features: ${..[0].out_features}
      out_features: 1
