regressor:
  _target_: src.rul_models.blocks.Regressor
  _args_:
    - _target_: torch.nn.Linear
      in_features: 50
      out_features: 25
   
    - _target_: torch.nn.Sigmoid
    - _target_: torch.nn.Dropout
      p: 0.25

    - _target_: torch.nn.Linear
      in_features: 25
      out_features: 12
   
    - _target_: torch.nn.Sigmoid
    - _target_: torch.nn.Dropout
      p: 0.25

    - _target_: torch.nn.Linear
      in_features: 12
      out_features: 1
   
