dataset:
  filename : 1
  batch_size : 128
model:
  in_channels : 14
  out_channels : 32
  kernel_size : 5
  maxpool_kernel : 3
  num_classes : 1
  hidden_size : 96
  num_layers : 4
  maxpool_stride : 2
  window_size : 30
training:
  learning_rate : 0.1
  epochs : 200
  patience: 2
  min_delta: 10
