conv_block_1:
  in_channels: 14
  out_channels: 32
  kernel_size: 5
  stride: 2
  padding: 2
  dilation: 1
  dropout: true
  dropout_rate: 0.25
  batch_norm: true
conv_block_2:
  in_channels: 32
  out_channels: 64
  kernel_size: 3
  stride: 1
  padding: 1
  dilation: 1
  dropout: true
  dropout_rate: 0.25
  batch_norm: true
lstm:
  input_size: 64
  output_length: 64
  hidden_size: 50
  dropout: 0.25
  batch_first: true
  bidirectional: false
  activation: ReLU
  num_classes: 1
  num_directions: 1
  num_layers: 1
lr: 0.015
model_path: ./model
checkpoint:
  monitor: val_loss
  mode: min
  save_top_k: 1
  verbose: true
