epochs: 1000
gradient_clip_val: 0.5
gradient_clip_algorithm: value
patience: 10
min_delta: 0.1
lr: 0.015
log_dir: ./logs
name: training
save_path: ./logs/training.log
resume: true
version: 0.1
git_sha: { git rev-parse HEAD | cut -c 1-8 }
git_branch: main